<?
$townList = array(

  array("name" => "Балашиха", "secondName" => "Балашихе"),
  array("name" => "Видное", "secondName" => "Видном"),
  array("name" => "Дедовск", "secondName" => "Дедовске"),
  array("name" => "Дзержинский", "secondName" => "Дзержинском"),
  array("name" => "Дмитров", "secondName" => "Дмитрове"),
  array("name" => "Долгопрудный", "secondName" => "Долгопрудном"),
  array("name" => "Домодедово", "secondName" => "Домодедово"),
  array("name" => "Дубна", "secondName" => "Дубне"),
  array("name" => "Егорьевск", "secondName" => "Егорьевске"),
  array("name" => "Железнодорожный", "secondName" => "Железнодорожном"),
  array("name" => "Жуковский", "secondName" => "Жуковском"),
  array("name" => "Звенигород", "secondName" => "Звенигороде"),
  array("name" => "Зеленоград", "secondName" => "Зеленограде"),
  array("name" => "Истра", "secondName" => "Истре"),
  array("name" => "Кашира", "secondName" => "Кашире"),
  array("name" => "Климовск", "secondName" => "Климовске"),
  array("name" => "Коломна", "secondName" => "Коломне"),
  array("name" => "Королёв", "secondName" => "Королёве"),
  array("name" => "Котельники", "secondName" => "Котельниках"),
  array("name" => "Красногорск", "secondName" => "Красногорске"),
  array("name" => "Краснознаменск", "secondName" => "Краснознаменске"),
  array("name" => "Ликино-Дулёво", "secondName" => "Ликино-Дулёво"),
  array("name" => "Лобня", "secondName" => "Лобне"),
  array("name" => "Лыткарино", "secondName" => "Лыткарино"),
  array("name" => "Можайск", "secondName" => "Можайске"),
  array("name" => "Мытищи", "secondName" => "Мытищах"),
  array("name" => "Наро-фоминск", "secondName" => "Наро-фоминске"),
  array("name" => "Ногинск", "secondName" => "Ногинске"),
  array("name" => "Одинцово", "secondName" => "Одинцово"),
  array("name" => "Орехово-зуево", "secondName" => "Орехово-зуево"),
  array("name" => "Подольск", "secondName" => "Подольске"),
  array("name" => "Протвино", "secondName" => "Протвино"),
  array("name" => "Пушкино", "secondName" => "Пушкино"),
  array("name" => "Раменское", "secondName" => "Раменском"),
  array("name" => "Реутов", "secondName" => "Реутове"),
  array("name" => "Сергиев Посад", "secondName" => "Сергиев Посаде"),
  array("name" => "Серпухов", "secondName" => "Серпухове"),
  array("name" => "Солнечногорск", "secondName" => "Солнечногорске"),
  array("name" => "Ступино", "secondName" => "Ступино"),
  array("name" => "Талдом", "secondName" => "Талдоме"),
  array("name" => "Троицк", "secondName" => "Троицке"),
  array("name" => "Фрязино", "secondName" => "Фрязино"),
  array("name" => "Химки", "secondName" => "Химках"),
  array("name" => "Чехов", "secondName" => "Чехове"),
  array("name" => "Щелково", "secondName" => "Щелково"),
  array("name" => "Электросталь", "secondName" => "Электростали"),
  array("name" => "Юбилейный", "secondName" => "Юбилейном")
  )
?>